[package]
name = "tomato-notify"
version = "1.1.0"
authors = ["Richard Yao <2501.owlsome@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
tokio = { version = "1", features = ["full"] }
